//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AafnoSawariEntities : DbContext
    {
        public AafnoSawariEntities()
            : base("name=AafnoSawariEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADDRESS> ADDRESSes { get; set; }
        public DbSet<ADVERTISEMENT> ADVERTISEMENTs { get; set; }
        public DbSet<CARIMAGE> CARIMAGES { get; set; }
        public DbSet<CAR> CARS { get; set; }
        public DbSet<CARTAG> CARTAGs { get; set; }
        public DbSet<LOGTABLE> LOGTABLEs { get; set; }
        public DbSet<MESSAGE> MESSAGES { get; set; }
        public DbSet<PROCESSTYPE> PROCESSTYPEs { get; set; }
        public DbSet<REVIEW> REVIEWS { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<USER> USERS { get; set; }
        public DbSet<VIDEO> VIDEOS { get; set; }
    }
}
