//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.ADDRESSes = new HashSet<ADDRESS>();
            this.ADVERTISEMENTs = new HashSet<ADVERTISEMENT>();
            this.CARIMAGES = new HashSet<CARIMAGE>();
            this.CARS = new HashSet<CAR>();
            this.CARS1 = new HashSet<CAR>();
            this.CARTAGs = new HashSet<CARTAG>();
            this.LOGTABLEs = new HashSet<LOGTABLE>();
            this.MESSAGES = new HashSet<MESSAGE>();
            this.REVIEWS = new HashSet<REVIEW>();
            this.VIDEOS = new HashSet<VIDEO>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ImagePath { get; set; }
        public bool isAdmin { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public System.DateTime AddDate { get; set; }
        public int LastUpdateUserID { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual ICollection<ADDRESS> ADDRESSes { get; set; }
        public virtual ICollection<ADVERTISEMENT> ADVERTISEMENTs { get; set; }
        public virtual ICollection<CARIMAGE> CARIMAGES { get; set; }
        public virtual ICollection<CAR> CARS { get; set; }
        public virtual ICollection<CAR> CARS1 { get; set; }
        public virtual ICollection<CARTAG> CARTAGs { get; set; }
        public virtual ICollection<LOGTABLE> LOGTABLEs { get; set; }
        public virtual ICollection<MESSAGE> MESSAGES { get; set; }
        public virtual ICollection<REVIEW> REVIEWS { get; set; }
        public virtual ICollection<VIDEO> VIDEOS { get; set; }
    }
}
